device: cuda
num_workers: 8

ckpt_dir: ./ckpt
ckpt_name: None
ckpt: None

resuming: False
ckpt_path: None

sr: 8000
num_label: 4


max_t: 3
min_t: 0.5

fft:
  n_mel: 24

augment:
  spec_aug:
    apply: true
    freq_mask_width: [0, 8]
    time_mask_width: [0, 10]
  noise:
    add: true
    path: None
    freq: 0.8
  min_val: 0.1


lr: 1e-3
weight_decay: 1e-6
epochs: 200
min_lr: 1e-5
max_lr: 0.001
lr_patience: 10
warmup_epoch: 5

batch_size: 32
patience: 10
dry_run: false
ites_dry_run: 5
verbose: false

tr: None
cv: None
