accum_grad: 4
cmvn_file: exp/conformer/global_cmvn
dataset_conf:
  batch_conf:
    batch_size: 8
    batch_type: static
  fbank_conf:
    dither: 0.1
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  filter_conf:
    max_length: 20480
    min_length: 0
    token_max_length: 100
    token_min_length: 1
  resample_conf:
    resample_rate: 16000
  shuffle: true
  shuffle_conf:
    shuffle_size: 1500
  sort: true
  sort_conf:
    sort_size: 500
  spec_aug: true
  spec_aug_conf:
    max_f: 10
    max_t: 50
    num_f_mask: 2
    num_t_mask: 2
  speed_perturb: true
decoder: transformer
decoder_conf:
  attention_heads: 4
  dropout_rate: 0.1
  linear_units: 64
  num_blocks: 3
  positional_dropout_rate: 0.1
  self_attention_dropout_rate: 0.0
  src_attention_dropout_rate: 0.0
encoder: conformer
encoder_conf:
  activation_type: swish
  attention_dropout_rate: 0.0
  attention_heads: 4
  cnn_module_kernel: 15
  dropout_rate: 0.1
  input_layer: conv2d
  linear_units: 64
  normalize_before: true
  num_blocks: 3
  output_size: 64
  pos_enc_layer_type: rel_pos
  positional_dropout_rate: 0.1
  selfattention_layer_type: rel_selfattn
  use_cnn_module: true
grad_clip: 5
input_dim: 80
is_json_cmvn: true
lfmmi_dir: ''
log_interval: 100
max_epoch: 240
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
optim: adam
optim_conf:
  lr: 0.002
output_dim: 187
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000
